.\" Process this file with
.\" groff -man -Tascii src-pkg-install.1
.\"
.TH SRC-PKG-INSTALL 1 "AUGUST 2007" Linux "User Manuals"
.SH NAME
src-pkg-install \- installs a source package 
.SH SYNOPSIS
.B src-pkg-install [-h] [-v] -k
.I key
.B [-d
.I distdir
.B ] [-p
.I portdir
.B ] -i 
.I input-package
.SH DESCRIPTION
.B src-pkg-install
verifies the signature of 
.I input-package
using the private key
.I key
, then installs the source package 
.I input-package
in both
.I distdir
(for the distfile) and
.I portdir
(for the portage files).
.SH MANDATORY PARAMETERS
.IP "-i input-package"
Specify the input source package to install.
.IP "-k key"
Specify the private key used to connect the CCSD library in order to verify the signature of the input package.
.SH OPTIONS
.IP -h
Display the help of the command.
.IP -v
Display the version of the tool.
.IP "-d distdir"
Specify the distfile directory where the command must install the package distfile.
.IP "-p portdir"
Specify the portdir directory where the command must install the portage tree of the package.
.SH RETURN VALUE
In case of error, 1 is returned. Otherwise, the command returns 0.
.SH AUTHOR
EADS Defence And Security Systems
.SH "SEE ALSO"
.BR verify-sign (1),
